# .github/workflows/everytime_autolike.yml

name: Everytime Auto-Like Automation

# 언제 이 Action을 실행할지 정의하는 부분
on:
  workflow_dispatch: # GitHub Actions 탭에서 수동으로 실행할 수 있게 함
  schedule:
    - cron: '0 1 * * *' # 매일 UTC 1시에 실행 (한국 시간 오전 10시)

# 어떤 작업을 수행할지 정의하는 부분
jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 (우분투 최신 버전)

    steps:
      # 1. 내 Repository의 코드를 Runner 환경에 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 사용 중인 파이썬 버전 입력

      # 3. Chrome 설치 (Selenium Manager가 드라이버 자동 관리)
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version  # 설치 확인용 로그

      # 4. 필요한 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. 메인 스크립트 실행 (headless 모드로)
      - name: Run automation
        run: python main.py everytime --headless
        env:
          EVERYTIME_USERNAME: ${{ secrets.EVERYTIME_USERNAME }}
          EVERYTIME_PASSWORD: ${{ secrets.EVERYTIME_PASSWORD }}

      # 6. 로그 파일 업로드
      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs/everytime_autolike.log

      # 7. 크롬 정리 
      - name: Clean leftover Chrome processes
          run: pkill -9 chrome || true